[workspace]
members = ["crates/protocol","crates/server"]
resolver = "3"

[workspace.dependencies]
goosekv-protocol = { path = "crates/protocol" }
glommio = { version = "0.9.0" }
bytes = { version = "1.10.1" }
thiserror = { version = "2.0.16" }
futures-lite = { version = "2.6.1" }

